[package]
name = "slpn"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
bumpalo = { version = "3.16.0", features = ["boxed", "collections"] }

[build-dependencies]
cmake = "0.1.51"
